### ISSUE TITLE
1.0.4 Won't boot on Pie, is this just for Q? 

### ISSUE THREAD

**Issue by Mike-Ferretti** [Juxstin/EdXposed-SnapChat-Bypass#1]
Figured I'd flash it to test it out and get the new (if any) Snapchat bypass updates you may have thrown in there. Completely removed Edxposed with the included uninstaller, flashed the YAHFA version you recommended, rebooted, and eventually got sent back to TWRP. Removed Edxposed again, flashed Sandhook version, same result. So my main question is, is this just for Q? Also, are you still supporting the current working 1.03 version that has been working wonderful for me on Pie? Thank you for your contribution to this community!

**Comment by DarshanDeshpande** [comment]
Not only pie but for me it bootloops on Q too. I tried the sandhook and the yahfa version and both looped for me

**Comment by Juxstin** [comment]
yes, its only for Q and @DarshanDeshpande ill post there offical Q one soon 👍

**Comment by sahils1702** [comment]
Best of luck . Waiting for it

**Comment by fooc-ctrl** [comment]
T

**Comment by FlorentLM** [comment]
It's bootlooping on Q too so...
