### ISSUE TITLE
Bootlop using snapchat varient of edxposed [BUG] 

### ISSUE THREAD

**Issue by Sobuj53** [Juxstin/EdXposed-SnapChat-Bypass#17]
**什么情况/What happened?**
flashed `magisk-riru-core-v19.5.zip` and `magisk-EdXposed-YAHFA-v0.4.6.4_beta.Justins.Fork.No.Custom.Magisk.zip` of `EdXposed-SnapChat-Bypass`, phone doesn't boot anymore.

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
MaxLock, LuckyPatcher
允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
viper4android, riru core, edxposed, audio_modification_Library, Busybox, youtube vanced,
允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: magisk-EdXposed-YAHFA-v0.4.6.4_beta.Justins.Fork.No.Custom.Magisk.zip

Riru: 19.5

**相关Logcat/Logcat**
[https://paste.ubuntu.com/p/6jcR2v8MC6/](url)
有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

PS: My magisk version is 20.3 beta,
I've tried the normal riru core 19.6 and edxposed - Yahfa variants, that one worked without issue.

**Comment by jobwan** [comment]
Same error here for a while. Try SandHook. No matter what I do, YAHFA won't boot for me. Hoping EdXposed gets the new custom magisk patch merged soon, and it gets pulled by this repository. Maybe then it'll work.

**Comment by jobwan** [comment]
@Sobuj53 Try my latest release and report back to me how it goes:

https://github.com/jobwan/EdXposed/releases/tag/v0.4.6.1

**Comment by SoumyBhow** [comment]
Thank you so much for your build, @Jobwan! I could only use Juxstin's Sandhook build since YAHFA caused bootloops, but it made my phone feel super sluggish. Your YAHFA build was just what I needed.

**Comment by Juxstin** [comment]
@SoumyBhow @jobwan released a SEPOLICY version feel free to try as you resolved now closed

**Comment by SoumyBhow** [comment]
This wasn't my issue. It was someone else's. I just wanted to thank Jobwan for his work since it resolved my problems with my device...

**Comment by jobwan** [comment]
> 
> 
> Thank you so much for your build, @jobwan! I could only use Juxstin's Sandhook build since YAHFA caused bootloops, but it made my phone feel super sluggish. Your YAHFA build was just what I needed.

I'm glad to hear that. :)

**Comment by Sobuj53** [comment]
@jobwan thank you for your hard work and sorry for the late response. Is your variant compatible with snapchat?

**Comment by jobwan** [comment]
@Sobuj53 It should be. I've synced the latest EdXposed from the sepolicy-branch and added in Juxstin's tweaks https://github.com/ElderDrivers/EdXposed/pull/387, and I've personally used it for the past five days without any issues. I couldn't get near that many days without getting banned using regular EdXposed.

**Comment by Sobuj53** [comment]
Thank you very much
