### ISSUE TITLE
SafetyNet still detected

### ISSUE THREAD

**Issue by xqzba** [Juxstin/EdXposed-SnapChat-Bypass#18]
Using your SEPolicy YAHFA build on Android 9 OneUI with LuckyPatcher module. I cannot seem to use your guide to fix SafetyNet. When I tried to blacklist Google Play Services, it says 'Failed to edit, one or more settings prevent you from editing'. I have enabled App List mode and Black/White list

**Comment by SoumyBhow** [comment]
Did you try blacklisting Google Services Framework, too? Both of them need to be blacklisted.
