### ISSUE TITLE
Snapchat Detected

### ISSUE THREAD

**Issue by xqzba** [Juxstin/EdXposed-SnapChat-Bypass#19]
Just got a temp ban twice in a row now using SEPolicy Sandhook with SafetyNet fix and LuckyPatcher only.

**Comment by Juxstin** [comment]
@xqzba what version? also could be your rom i don't get a ban

**Comment by xqzba** [comment]
> @xqzba what version? also could be your rom i don't get a ban

Sorry for blaming on this again, it was my rom. They released a patch yesterday and it's working fine now.
