### ISSUE TITLE
Bootloop YAHFA 1.0.3

### ISSUE THREAD

**Issue by Senliast** [Juxstin/EdXposed-SnapChat-Bypass#2]
I am getting bootloop with YAHFA 1.0.3, with SandHook it boots ,but sometimes on boot hangs on 'Phone ist starting', and I must reboot it. Can you please fix it or reupload v.1.0.2?

Pixel 2, Pie, tested with no modules installed.

**Comment by pokemontotalwar** [comment]
I'm experiencing the same,

OnePlus 6T, Pie, tested with no modules enabled

**Comment by Juxstin** [comment]
@Senliast @pokemontotalwar unfortunately that won't fix it wait till edxposed fixes

**Comment by fooc-ctrl** [comment]
I'm having a bootloop on yahfa. I'm also having issues with sandhook, I keep having random restarts. Please help. OnePlus 7 pro on Android 9 havocOS.
