### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by retromi** [Juxstin/EdXposed-SnapChat-Bypass#20]
**什么情况/What happened?**
I installed your framework and it successfully keeps my snapchat unbanned. Unfortunately my system started working really slow. I ve got a custom Samsung Galaxy note fe's rom (pie)  on my galaxy s7. Is there any solution?

**Xposed模块列表/Xposed Module List**
None
**Magisk模块列表/Magisk Module List**
YouTube Vanced
Viper4Android
Riru Core
Samsung 4k60 camera
Edxposed beta snapchat version no custom magisk

**Comment by Juxstin** [comment]
@retromi its your rom.

**Comment by retromi** [comment]
ok thx for reply
