### ISSUE TITLE
Xiaomi mi9 issues

### ISSUE THREAD

**Issue by Kajakas** [Juxstin/EdXposed-SnapChat-Bypass#22]
The edxposed fork causes my Android 10 xiaomi.eu rom to bootloop, if I switch back to normal edxposed 4.6.1, issues remain, some modules don't load, overall device lag, takes several minutes to restart etc. Had to wipe /data and start over. I hate Snapchat, I wish people stopped using it.

**Comment by Juxstin** [comment]
@Kajakas Try https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases/tag/1.1.0
