### ISSUE TITLE
[BUG] Can't pass SafetyNet after the last update 

### ISSUE THREAD

**Issue by gruber013** [Juxstin/EdXposed-SnapChat-Bypass#25]
**什么情况/What happened?**

After updating to latest YAHFA 0.4.6.5 (Justins Fork) I can't pass SafetyNet pass : ctsProfile nor BasicIntegrity. I have updated my edXposed manager to 4.5.5 but nothing else got updated nor changed. 
It used to be 50 - 50 but now I keep failing when it comes to SafetyNet. 

Yes, I have blacklisted required apps. 

**Xposed模块列表/Xposed Module List**

InstaPrefs, Exi for SwiftKey, MinMinGuard, Xposed Edge. 

**Magisk模块列表/Magisk Module List**

OOS Call Recorder, Riru Core, edXposed, some font and emoji module, GPay Fix Module, SQLite and SafetyPatch. 

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.6.5 (Justins Fork) (YAHFA) 

Riru: 19.7

**Comment by doclucas** [comment]
Same here, also when using 0.4.6.1 Sandhook and Yahfa.

**Comment by doclucas** [comment]
By the way. I'm on Note 10 N975F Android 10 March 1st security patch.
This might be related :
https://android.stackexchange.com/questions/221976/magisk-will-fail-safety-net-hereafter-why

Important to note that magisk still pass safety net when I disable edxposed.

**Comment by virginsince1997** [comment]
> By the way. I'm on Note 10 N975F Android 10 March 1st security patch.
> This might be related :
> https://android.stackexchange.com/questions/221976/magisk-will-fail-safety-net-hereafter-why
> 
> Important to note that magisk still pass safety net when I disable edxposed framework.

Please can you assist me on how to install this tool on my pixel 2xl, 9

**Comment by virginsince1997** [comment]
Same here, I just installed the repo and safe net fails, android pie
![Screenshot_20200402-232954](https://user-images.githubusercontent.com/21218962/78306309-f9ef8b80-753a-11ea-84f1-76beb91abc24.png)

**Comment by Mnky313** [comment]
> By the way. I'm on Note 10 N975F Android 10 March 1st security patch.
> This might be related :
> https://android.stackexchange.com/questions/221976/magisk-will-fail-safety-net-hereafter-why
> 
> Important to note that magisk still pass safety net when I disable edxposed framework.

Exactly the same here Note9 N9600 Android 10 March 1st patch

**Comment by SoumyBhow** [comment]
The new Edxposed version, 4.6.3 (4532) passes SN, so we'll have to wait for Juxstin to update the Snapchat version...

**Comment by doclucas** [comment]
> The new Edxposed version, 4.6.3 (4532) passes SN, so we'll have to wait for Juxstin to update the Snapchat version...

Can't find version 4.6.3 (4532). Where do you see it?

**Comment by Mnky313** [comment]
> Can't find version 4.6.3 (4532). Where do you see it?
It's the latest canary version, I just tried it and yeah, SafetyNet works.

**Comment by gruber013** [comment]
Actually it's the Google who changed SafetyNet triggers recently, all edXposed versions seems to cause SafetyNet to break and there's no way currently to change that unless you disable edXposed.

Also, if you want to see more just check Magisk General Discussion thread on XDA.

**Comment by doclucas** [comment]
But Mnky313 says SafetyNet works with the new canary version?

**Comment by gruber013** [comment]
> But Mnky313 says SafetyNet works with the new canary version?

You're right actually, it's been fixed (for now) in canary build.

**Comment by Mike-Ferretti** [comment]
Well it's great that it's working in the canary version, but I rely on Snapchat too much to risk going to the canary version and then getting banned. Hopefully Justin can sync that repo and work his magic to get us to pass SN without losing the Snapchat blocking capabilities! :)

**Comment by gruber013** [comment]
I personally just installed Taichi and I'll stay there since I'm only using InstaPrefs, Exi and XposedEdge - I'm finally passing SafetyNet 100% of time and it doesn't interfere with Snapchat's rules.

**Comment by virginsince1997** [comment]
> Well it's great that it's working in the canary version, but I rely on Snapchat too much to risk going to the canary version and then getting banned. Hopefully Justin can sync that repo and work his magic to get us to pass SN without losing the Snapchat blocking capabilities! :)

Can you help me out? I need help with some questions about this repo, telegram?

**Comment by Juxstin** [comment]
https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases/tag/1.1.1
