### ISSUE TITLE
[BUG] Bootloop on the latest version

### ISSUE THREAD

**Issue by gruber013** [Juxstin/EdXposed-SnapChat-Bypass#27]
**什么情况/What happened?**

Phone is stuck in bootloop after flashing YAHFA version while edXposed prompts that Framework is not installed after flashing SandHook version. 

RiruCore flashed and I have fully working Magisk. 

OnePlus 5, OOS 9.0.10 (stock) 

**Xposed模块列表/Xposed Module List**

None. 

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 4.5.7

Riru: 19.8

**Comment by Juxstin** [comment]
@gruber013 ye seems this update has issues for OnePlus's ill post when they fix :)

**Comment by Juxstin** [comment]
Ok so seems a big issue reverted commits waiting on EdXposed to fix then ill push update
