### ISSUE TITLE
Latest version for Pie?

### ISSUE THREAD

**Issue by Mike-Ferretti** [Juxstin/EdXposed-SnapChat-Bypass#3]
Is 1.0.3 still the latest for Pie? (9.0)

**Comment by Juxstin** [comment]
@Mike-Ferretti yes but you can try 1.0.5 up to you

**Comment by Mike-Ferretti** [comment]
> @Mike-Ferretti yes but you can try 1.0.5 up to you

I just tried, it eventually booted back into recovery with both versions.

**Comment by Mike-Ferretti** [comment]
Any chance you could update 1.0.3 to EdXposed-SandHook-v0.4.6.0_beta.Justins.Fork.-release.zip as an upgrade over the current and I suppose older version? :)

**Comment by Juxstin** [comment]
@Mike-Ferretti you need to use custom magisk i updated the README.md https://github.com/Juxstin/EdXposed-SnapChat-Bypass/blob/offical-q-support/README.md#install

**Comment by Mike-Ferretti** [comment]
I've done all those. 1.0.5 just boots for like 5-10 minutes and goes to recovery, 1,0.3 works perfectly though, I just wanted to use 1.0.5 because of the updates.

**Comment by Mike-Ferretti** [comment]
Okay so I added the repo you added in the README and it's stuck on "checkingn for updates" Was I supposed to copy/paste the ENTIRE thing as one URL?

**Comment by Juxstin** [comment]
@Mike-Ferretti you should add it then force close magisk manager and reopen

**Comment by Juxstin** [comment]
OR you can use  https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases/download/1.0.6/magisk-EdXposed-SandHook-v0.4.6.1_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip

**Comment by Mike-Ferretti** [comment]
Working perfectly, thank you!

**Comment by Mike-Ferretti** [comment]
Question, what does the no custom magisk mean?

**Comment by pokemontotalwar** [comment]
> Question, what does the no custom magisk mean?

A lot of devices don't need to run the custom Magisk build, but the developers disabled the script in EdXposed that allows it to work without the custom Magisk, for maximum compatibility. If your device doesn't require the custom Magisk, and it was working before the latest versions, the no custom Magisk build just reenables that script. That way you can continue to run official Magisk builds.

**Comment by Juxstin** [comment]
Solved / Closed
