### ISSUE TITLE
SafetyNet Fail

### ISSUE THREAD

**Issue by chihb** [Juxstin/EdXposed-SnapChat-Bypass#30]
When the Riru Core module is enabled the SafetyNet check fails to pass.

**Comment by poweromania** [comment]
For me RiruCore 19.8 passes safetynet but fails when i activate SandHook v0.4.6.5 by Juxstin

**Comment by chihb** [comment]
> For me RiruCore 19.8 passes safetynet but fails when i activate SandHook v0.4.6.5 by Juxstin

Same here, don't know if it'll be fixed

**Comment by Juxstin** [comment]
blame google lol
