### ISSUE TITLE
[REQUEST] Provide versions that do not require custom Magisk

### ISSUE THREAD

**Issue by pokemontotalwar** [Juxstin/EdXposed-SnapChat-Bypass#5]
In the latest versions of EdXposed, you are required to install a custom Magisk build. On devices that do support supolicy, if you revert the post-fs-data.sh, it works fine on the official Magisk build. Can builds that include the supolicy tweaks in post-fs be provided?

Also, can the README/description be updated with a link to the custom Magisk build?

**Comment by Juxstin** [comment]
@pokemontotalwar https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases/download/1.0.5/magisk-EdXposed-SandHook-v0.4.6.0_beta.Justins.Fork.-release.NO.CUSTOM.MAGISK.zip

**Comment by chriscrox** [comment]
> 
> 
> @pokemontotalwar https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases/download/1.0.5/magisk-EdXposed-SandHook-v0.4.6.0_beta.Justins.Fork.-release.NO.CUSTOM.MAGISK.zip

Could you do this for YAHFA as well? SandHook doesn't work on all modules for me, but YAHFA does.

**Comment by pokemontotalwar** [comment]
> > @pokemontotalwar https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases/download/1.0.5/magisk-EdXposed-SandHook-v0.4.6.0_beta.Justins.Fork.-release.NO.CUSTOM.MAGISK.zip
> 
> Could you do this for YAHFA as well? SandHook doesn't work on all modules for me, but YAHFA does.

Agreed -- Sandhook makes my device reboot at random intervals. In the meantime, though, you can just download the Sandhook one, pull the post-fs-data.sh from it, and drop it in the installed Module. It'll do the same thing as a no custom build for YAHFA, just extra steps

**Comment by Juxstin** [comment]
@pokemontotalwar @chriscrox https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases/download/1.0.6/magisk-EdXposed-YAHFA-v0.4.6.1_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip

**Comment by Juxstin** [comment]
Done / Solved

**Comment by chriscrox** [comment]
> 
> 
> @pokemontotalwar @chriscrox https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases/download/1.0.6/magisk-EdXposed-YAHFA-v0.4.6.1_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip



> 
> 
> Done / Solved

Thank you very much. Has been working perfectly for the last four days without any errors. :)

**Comment by chriscrox** [comment]
@pokemontotalwar Do you by any chance still have magisk-EdXposed-YAHFA-v0.4.6.1_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip? If so, could you send it to me, as the link is no longer working?
