### ISSUE TITLE
error.stuck in bootloop

### ISSUE THREAD

**Issue by hsheidaryarad** [Juxstin/EdXposed-SnapChat-Bypass#7]
hi justin,please help me,i use xposed framework 4.5.5 fro u and very good, but since i use to latest version 4.6.0 or 4.6.1 from you my phone stuk in boot, and i have to format data on recovery,
i want to use latest version of everyting specialy xposed, 
my phone is galaxy s7 edge android 8.plz help me sooooooonnnnn

**Comment by hsheidaryarad** [comment]
please help me to use this latest version on my phone, I use to custom magisk from ian or canary

**Comment by Juxstin** [comment]
@hsheidaryarad try this https://github.com/Juxstin/EdXposed-SnapChat-Bypass/releases/download/1.0.6/magisk-EdXposed-SandHook-v0.4.6.1_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip

**Comment by hsheidaryarad** [comment]
Hi again just in,again stuck in boot loop an I had to format all of my data on phone ,I don't format data again and again,please help me,I'd like to use you're latest version,my phone is (s7 edge  middle East chip set and android8  security patch September, I wait for your soloution

**Comment by hsheidaryarad** [comment]
Also I use ian custom private magisk

**Comment by Mike-Ferretti** [comment]
Try using the NOCUSTOMMAGISK version.

**Comment by hsheidaryarad** [comment]
> Try using the NOCUSTOMMAGISK version.

thank u. are u sure work fine with this mike

**Comment by Mike-Ferretti** [comment]
It works on my phone. The regular version didn't work so I flashed the NOCUSTOMMAGISK version and it worked.

**Comment by hsheidaryarad** [comment]
> It works on my phone. The regular version didn't work so I flashed the NOCUSTOMMAGISK version and it worked.

its work for me tooo.thanks alot miky

**Comment by Mike-Ferretti** [comment]
No problem! :)
