### ISSUE TITLE
Stuck in Bootloop

### ISSUE THREAD

**Issue by hermiej** [Juxstin/EdXposed-SnapChat-Bypass#9]
I tried flashing the module, as I tried rebooting I got stuck in a bootloop. I am using a Google Pixel 3 Xl, android pie, and I am on magisk 20.1 .

**Comment by Mike-Ferretti** [comment]
Try using the NOCUSTOMMAGISK version.

**Comment by Juxstin** [comment]
@hermiej yes try @Mike-Ferretti solution

**Comment by chriscrox** [comment]
@hermiej, which zip-file did you use?

I used magisk-EdXposed-YAHFA-v0.4.6.1_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip for a while, but it's no longer here, so I had to use magisk-EdXposed-YAHFA-v0.4.6.3_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip and it bootloops no matter what I do.

My setup is Samsung Galaxy Note 3 HLTE, LineageOS 16.0, Magisk 20.1 and magisk-riru-core-v19.5.zip from the same folder release page as magisk-EdXposed-YAHFA-v0.4.6.3_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip.

This one works without bootloops and errors, but isn't tweaked for Snapchat:
https://forum.xda-developers.com/showpost.php?p=80660829&postcount=92

**Comment by chriscrox** [comment]
@Juxstin could you reupload magisk-EdXposed-SandHook-v0.4.6.1_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip, so I can test it out and see if it works or if it boot?loops If it bootlops, then I know it's my phone there's something wrong with, as 0.4.6.1 worked perfectly last time I had it installed.

**Comment by chriscrox** [comment]
@Juxstin could you reupload magisk-EdXposed-YAHFA-v0.4.6.1_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip? If 0.4.6.1 works, then I know it's my phone that has some issues, as 0.4.6.1 was working perfectly last time I had it installed.

**Comment by chriscrox** [comment]
UPDATE: magisk-EdXposed-SandHook-v0.4.6.3_beta.Justins.Fork.NO.CUSTOM.MAGISK.-release.zip works perfectly with no bootloop at all, but unfortunately some of my modules only works on half the settings, which is why I need YAHFA-variant. Will test out more and update.

**Comment by amakuramio** [comment]
@chriscrox on s9 no versions work on q, straight to twrp, all other versions than 20.2 no root
Did you get it working by flashing official 20.2 plus no custom magisk?

**Comment by jobwan** [comment]
@chriscrox Having same issue here. YAHFA won't work no matter what, but SandHook works without issue. Unfortunately SandHook only gives me two out of four options for XInsta, whilst YAHFA gave me all four.

@amakuramio I use Magisk 20.1 (still waiting for topjohnwu to update Magisk Canary, as I can't compile myself) and downloaded Juxstin's latest SandHook (NoCustomMagisk) zip and flashed that.

**Comment by amakuramio** [comment]
> @chriscrox Having same issue here. YAHFA won't work no matter what, but SandHook works without issue. Unfortunately SandHook only gives me two out of four options for XInsta, whilst YAHFA gave me all four.
> 
> @amakuramio I use Magisk 20.1 (still waiting for topjohnwu to update Magisk Canary, as I can't compile myself) and downloaded Juxstin's latest SandHook (NoCustomMagisk) zip and flashed that.

On s9 q this causes twrp bootloop

**Comment by jobwan** [comment]
> 
> 
> > @chriscrox Having same issue here. YAHFA won't work no matter what, but SandHook works without issue. Unfortunately SandHook only gives me two out of four options for XInsta, whilst YAHFA gave me all four.
> > @amakuramio I use Magisk 20.1 (still waiting for topjohnwu to update Magisk Canary, as I can't compile myself) and downloaded Juxstin's latest SandHook (NoCustomMagisk) zip and flashed that.
> 
> On s9 q this causes twrp bootloop

I'm also on the S9, but I'm on LineageOS 16. That might be why it's not working for you. Perhaps Android Q is not fully supported yet.

**Comment by amakuramio** [comment]
> > > @chriscrox Having same issue here. YAHFA won't work no matter what, but SandHook works without issue. Unfortunately SandHook only gives me two out of four options for XInsta, whilst YAHFA gave me all four.
> > > @amakuramio I use Magisk 20.1 (still waiting for topjohnwu to update Magisk Canary, as I can't compile myself) and downloaded Juxstin's latest SandHook (NoCustomMagisk) zip and flashed that.
> > 
> > 
> > On s9 q this causes twrp bootloop
> 
> I'm also on the S9, but I'm on LineageOS 16. That might be why it's not working for you. Perhaps Android Q is not fully supported yet.

On stock q not working, on lineage 17 works fine. I'm on lineageos.

**Comment by jobwan** [comment]
@amakuramio Try my latest release and report back to me how it goes:

https://github.com/jobwan/EdXposed/releases/tag/v0.4.6.1

**Comment by kurtextrem** [comment]
> @amakuramio Try my latest release and report back to me how it goes:
> 
> [jobwan/EdXposed@`v0.4.6.1` (release)](https://github.com/jobwan/EdXposed/releases/tag/v0.4.6.1)

Thank you for this, at least for me it's working fine!

**Comment by jobwan** [comment]
> 
> 
> > @amakuramio Try my latest release and report back to me how it goes:
> > [jobwan/EdXposed@`v0.4.6.1` (release)](https://github.com/jobwan/EdXposed/releases/tag/v0.4.6.1)
> 
> Thank you for this, at least for me it's working fine!

Good to hear. :)
